# Generated by Django 4.1.5 on 2023-02-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_registerdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerdb',
            new_name='addregister',
        ),
    ]
