# Generated by Django 4.1.5 on 2023-02-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactdb',
        ),
    ]
