# Generated by Django 4.1.5 on 2023-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_delete_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
